### ISSUE TITLE
Add support for the "youtube.search.list" endpoint method

### ISSUE THREAD

**Issue by abjerner** [abjerner/Skybrud.Social.Google#1]
> Returns a collection of search results that match the query parameters specified in the API request. By default, a search result set identifies matching video, channel, and playlist resources, but you can also configure queries to only retrieve a specific type of resource.

Documentation: https://developers.google.com/youtube/v3/docs/search/list

API Explorer: https://developers.google.com/apis-explorer/?hl=en_US#p/youtube/v3/youtube.search.list

Example API URL: https://www.googleapis.com/youtube/v3/search?key={key}&channelId={channelId}&part=snippet,id&order=date&maxResults=50&type=youtube#video

**Comment by inovacode** [comment]
I would love to see support for this endpoint!  :-)

**Comment by abjerner** [comment]
Closing this issue in favor of: https://github.com/abjerner/Skybrud.Social.Google.YouTube/issues/1
