### ISSUE TITLE
Analytics Reporting API v4 Migration

### ISSUE THREAD

**Issue by TomSteer** [abjerner/Skybrud.Social.Google#6]
The current analytics service uses the v3 API. Would be great to migrate this to the v4 version. The link below gives some information on this:

https://developers.google.com/analytics/devguides/reporting/core/v4/migration

**Comment by abjerner** [comment]
@TomSteer thanks a lot for reporting. I wasn't aware there was a new version out - I will look into that ;)

**Comment by abjerner** [comment]
I haven't really worked on the Analytics part for a while, so not sure whether the v3 API still works.

Anyways, the implementation for each API has been moved to individual packages, so I'm closing this issue and have created https://github.com/abjerner/Skybrud.Social.Google.Analytics/issues/1
