### ISSUE TITLE
 Google+ shutdown notice

### ISSUE THREAD

**Issue by leekelleher** [abjerner/Skybrud.Social.Google#7]
Hi @abjerner, I'm not sure if this impacts the Skybrud.Social.Google authentication?

I got an email from Google about this flagging the OAuth API on one of our projects, (that we're only using with the Skybrud Social Google provider, with the Umbraco package).  I'm not sure how this impacts that?

https://developers.google.com/+/integrations-shutdown

Ignore this if you've already got it covered, etc. Thanks!

**Comment by abjerner** [comment]
Hi Lee,

I've started to see these notifications as well. I haven't fully looked into yet, but from what I can tell, this only applies to Google+. The authentication should still work - just not if you request any Google+ scopes or try to access the Google+ API.

The `openid` scope as described [here](https://social.skybrud.dk/google/scope/) may be a Google+ scope.

Anyways, I'll need to look into this to make sure. I'll report back what I find ;)

**Comment by leekelleher** [comment]
I got a follow-up clarification email from Google this morning...

> The email listed that one or more of your projects are requesting the “plus.me” scope, and would thus be affected. We would like to clarify that only projects **directly requesting the “plus.me” scope are affected**. This scope may have been listed in some emails, even if not directly requested by your project. We apologize for any confusion caused.

From what I recall, the Umbraco package doesn't show the "plus.me" scope in the config overlay.

**Comment by abjerner** [comment]
Probably about time to close this issue. Thanks for raising the issue initially 👍
